### PR TITLE
Modelling QCD background of W signal

### PR DESCRIPTION
**Pull request by lmcairns-mphys**
#28 

Hi @mvesteri 
Here is my attempt at creating a fit model for the W signal. I believe I've managed to create a sum histogram from the background template and the isolated signal, but I'm unsure if I've done it correctly.

I am additionally unsure how to "compare it to the data"? Do I need to subtract the fit model from the isolated muon data?

### CODE REVIEW

**Comment by mvesteri** [comment]
👍 @lmcairns did you intend to upload a figure/plot?

Regarding the data comparison. What I mean is to make something like the figure below. OK, a much simpler version with only one charge, and only the top part of the figure. You see that the black points are the real data. And then there are all of the fit components stacked on top of each other. And the sum of these is the "fit model". In your case it would just be the signal and hadron background components. Does that make sense?  

The easiest way to plot the two components stacked on top of each other is to make one histogram that is the [fraction]weighted sum. Plot that first. The plot one of the components by itself. (It will appear like a stacked histogram now). And then plot the data points last.

image

**Comment by lmcairns-mphys** [comment]
W_fit_model
@mvesteri 
I have updated my code in order to make a comparison plot. What are the next steps?

**Comment by mvesteri** [comment]
@lmcairns maybe you forgot to scale the blue histogram? 
I think the logic is like [pseudocode]
```
create_and_fill [data_hist, signal_hist, background_hist]
signal_fraction = 0.5 # guess
signal_hist.Scale(signal_fraction*data_integral/signal_integral)
background_hist.Scale((1-signal_fraction)*data_integral/background_integral)
model_hist = signal_hist + background_hist
TCanvas c
model_hist.Draw('HIST')
background_hist.Draw('HIST SAME')
data_hist.Draw('SAME E')
```

**Comment by lmcairns-mphys** [comment]
@mvesteri ahhhh yes, I had scaled the background by signal fraction as opposed to (1 - signal fraction) oops. Here's the corrected plot, with fraction = 0.5.
W_fit_model

**Comment by mvesteri** [comment]
OK, but now the sum [signal+background] is higher than the data. I think the sum must have the same integral of the data by definition. (It won't have exactly the same *shape*, because our model is still basic/inaccurate at this stage)

**Comment by lmcairns-mphys** [comment]
Okay, it seems I've misunderstood. What's the difference between signal_hist and data_hist? I've been using the same thing for both.

**Comment by mvesteri** [comment]
Data hist is the isolated muon data from the files ending with `EW.root`.
`signal_hist` is the W -> munu simulation. Files with `_W_` in them.

*`signal_hist` -> just signal *simulation
*`data_hist` -> real data that includes a mixture of signal and background

**Comment by lmcairns-mphys** [comment]
Okay, hopefully this is correct now? The plot looks strange but I assume that is due to the exponential fit.
W_fit_model

**Comment by mvesteri** [comment]
Great. That now looks as I expect.
You could try to 
1) generate more exponential events to fill your histogram template
2) try a steeper exponential function (just tweak the slope parameter)

**Comment by mvesteri** [comment]
Maybe you can also take a look now at https://root.cern.ch/doc/v606/classTFractionFitter.html

**Comment by lmcairns-mphys** [comment]
I have updated my exponential fit to generate 100,000 events for the template, as seen in the figure below, improving the template. I have also increased the slope to 2.5, although I cannot see much noticeable difference; increasing about 2.8 gives an uncertainty on the fit matrix of 100% and no plot is produced.
W_fit_model

I have attempted to include TFractionFitter in my code (see commented out, lines 120-135) but I received an error:
`Warning in <TFractionFitter::FindPrediction>: Did not find solution for t_i in 100000 iterations`

What would be the process of correcting this? What are the next steps?
Hope you are well! :)

**Comment by mvesteri** [comment]
@lmcairns it seems that your signal template is a bit statistically limited.
Can I first suggest changing the plot style slightly.
Instead of doing a stacked histogram, just *separately* draw the signal and background templates as unfilled histograms.
And then draw the sum/model and data as you do.

Then we can do a bit of investigation into the signal histogram

**Comment by lmcairns-mphys** [comment]
W_fit_model_separate
Here is each template plotted separately. The signal decay tree contains 4442 events, compared to 100000 in the background template and 373713 in the data decay tree.

**Comment by lmcairns-mphys** [comment]
1. I have editted the slope of the background template. Setting slope = 0.2 I get the following plot, which appears to fit a lot better:
W+_fit_model
2. I have altered my code to include a number of functions so that the analysis can be simultaneously performed for W+ and W-. 
These include:
- make_histogram -> creates and returns histogram from chain and file_path input
- background_fit -> fits background data with expo, outputs plot, creates and returns background_template
- produce_fit_model -> creates fit model histogram and outputs data comparison
- fraction_fitter -> performs TFractionFitter and outputs plot
3. Output of TFractionFitter for W+:
W+_fraction_fit
Is there an easy way to add the fit fractions to a statbox, similarly to SetOptFit for fitted function? 
I've found a work around (by adding them to the legend), but it seems like a messy solution to me. (This is commented out in the fraction_fitter function).
4. I haven't yet added the Z component, this is my intended next step.

**Comment by mvesteri** [comment]
* The fit now looks much better @lmcairns 
* Regarding printing the fit results on the plot: I don't think there is an automatic way of doing this. However, you can use `TPaveText`. Rough `C++` implementation copied below.

```cpp
#include <TPaveText>
//...
TPaveText statBox(0.1,0.7,0.3,0.9,"NDC");
statBox.SetFillStyle(0)
statBox.AddText(some_std_string.c_str());//expects char * (annoying that root doesn't natively support std::string)
//add more rows of text
statBox.Draw()
```

**Comment by lmcairns-mphys** [comment]
I have included Z background. Find below plots of the fraction fitter and the fit model for W+ and W- using the "WpIso" and "WmIso" decay trees in the _Z_ file respectively. These plots have been created using the fractions calculated in TFraction Fitter.

I had a few questions:
1. What is the best way to fix the fraction of Z background in TFractionFitter? I'm currently using `fit->Constrain(2,0.2,0.21);` as I had issues with the method used on the TFractionFitter class reference (set parameter).
2. Should I account for errors on the fractions when scaling the histograms in the fit model?
3. Would it be useful to include the fractions on the data comparison plot?
4. Would it be correct to label the Z background as "Electroweak" on the data comparison plot?

It is also worth noting that the Z simulation data are also statistically limited:
- Z, WpIso = 5020 entries
- Z, WmIso = 5303 entries
- W signal, WpIso = 4442 entries
- W signal, WmIso = 3123 entries

W-_fit_model
W-_fraction_fit
W+_fit_model
W+_fraction_fit

**Comment by mvesteri** [comment]
@lmcairns Plot including Z looks good 
* Yes I think you use the `Constrain` function with `TFractionFitter`. Note though that a "constrained" fraction could still float. If you want to *fix* a fraction then you need to constrain it with zero error.
* When scaling the histograms to make the plot I think you have to just ignore the errors. 
* Yes you could include the fractions if you want. That just requires using `std::to_string` or `std::ostringstream` to create the text yourself.
* I think it is clearer if you label the Z component as "Z" rather than "EW".

So the next step is to try and properly predict he Z background fraction.

You should be able to do this with these three quantities
* The number of Z events in the Z tree in data.
* The number of Z events in the Z tree in simulation.
* The number of Z events in the W tree in simulation.
* (Actually those would give you the predicted number of Z events, so you still need the number of W events to get a fraction)

**Comment by lmcairns-mphys** [comment]
Okay, just to check a few assumptions for counting the number of Z events, I'm assuming that:
- I need to include the kinematic cuts (same as before) when counting each of these?
- I get the number of W events from the data (using WpIso or WmIso)?
- "Z tree in simulation" means Z events in the "Z" decay tree in the `_Z_` simulation?
- I would assume that "W tree in simulation" would mean the same but for the `_W_` simulation, but there isn't a "Z" decay tree in this file. How should I calculate this?

Additionally, in terms of constraining the Z fraction, is it reasonable to set the upper and lower bounds in the `Constrain(parameter,lower,upper)` function to the calculated Z fraction ± its error?

**Comment by mvesteri** [comment]
* Yes, when counting the number of Z events it is probably best to include the same selection cuts that you had for the Z cross section study. 
* Yes for the number of W events. 
* Yes with `_Z_` in the file name. And then the `Z/DecayTree` path
* You don't need "W tree in simulation" for this estimate.

To *fix* the fraction you need to set the lower=upper=value. You could put in the actual error and then `TFractionFitter` will try to float the Z fraction with this constraint. That effectively means that there is another term in the chi2 that penalises parameter values that deviate far from the prediction.

**Comment by lmcairns-mphys** [comment]
Understand that I need to fix the fraction, but I am unsure how to do this. 
`Constrain()` doesn't work for this purpose as setting lower=upper unconstrains the value, and I have had issues with the TVirtualFitter method suggested on the TFractionFitter page. How would I best do this?

**Comment by mvesteri** [comment]
OK, for now maybe just set the uncertainty on this fraction to something arbitrary/small, e.g., 1%.

**Comment by lmcairns-mphys** [comment]
Using the number of Z events in the Z data and Z sim, I have calculated the fractions:
- Wp_Z_fraction = 0.046457 ± 0.001883
- Wm_Z_fraction = 0.058964 ± 0.002411
These feel small compared to the 10 or 20% you suggested previously, and looks small in the plot below.

The kinematic cuts used were:
- For Z events: "Z_M > 60.e3 && Z_M < 120.e3 && mup_PT > 20.e3 && mum_PT > 20.e3 && mup_ETA > 2 && mup_ETA < 4.5 && mum_ETA > 2 && mum_ETA < 4.5"
- For W events: "mu_PT > 20.e3 && mu_ETA > 2 && mu_ETA < 4.5"
W-_fit_model

To do this, I reused the `Constraint()` function, seen in line 185. I'm really unsure about the best way to do this. You mention that I should set the uncertainty on the parameter, and fix the value, but I am unsure how to do this. I have commented out some code in lines 186 to 187 which uses the suggested method on the TFractionFitter reference but I get errors when I use it relating to the data type ROOT::Fit::Fitter.

**Comment by mvesteri** [comment]
@lmcairns perhaps you could update your "automatic" latex report to include these new plots with the W data? And then add some formulae and description of how you predict the Z background fraction? I think it would be most efficient to check that we agree at the level of written formulae, and then we can go and check that the code is consistent with the formulae. Does that sound reasonable?

I think it is quite natural now that the fits with the W data become a new section/chapter in your existing study with the Z.

**Comment by mvesteri** [comment]
Writing the prediction formulae in latex is also essential for your report, so no harm in tackling that now 😄

**Comment by lmcairns-mphys** [comment]
@mvesteri 
Hi Mika,
Sorry I haven't uploaded the analysis report yet, I've had a bad weekend for migraines so haven't been able to do work until today.
I did realise I had made some errors in the calculation of the Z fraction at the end of last week. This has hopefully been corrected now, although I'm still not completely confident. The new equation can be seen in the last commit, and additionally in the screenshot below, from the analysis report I am currently writing:
Screenshot_Z_frac_eqn
This gives the Z fractions as:
Wp: 0.057 ± 0.003
Wm: 0.077 ± 0.004 (plot given below)
which seem a bit more realistic than my previous values (which seemed a bit small).
W-_fit_model

**Comment by mvesteri** [comment]
That looks great. The estimated Z fractions that you report are with your estimate of the statistical uncertainty (from the statistics of all three counts that go into the formula)?
If so: it would be ideal to use these in the `TFractionFitter` constraints, rather than some arbitrary number.

**Comment by lmcairns-mphys** [comment]
I have updated the code so that it uses statistical uncertainty to constrain Z fraction, as previous.
The statistical uncertainity is calculated using sqrt(N)/N for each of the 4 counts used to calculate Z fraction:
- W in Z sim
- Z in Z sim
- Z in data
- W in data
W-_fit_model

**Comment by mvesteri** [comment]
This looks great @lmcairns - suggest to push on towards a first version of your "automated" document including these main figures and the Z, W+ and W- cross sections. No need to write any new text at this stage. I'd be very interested to see this document, and then we can discuss the next steps.

**Comment by lmcairns-mphys** [comment]
[measurement_report.pdf](https://github.com/r-preston/MPhysProject2021/files/5962624/measurement_report.pdf)

Please find attached the automated analysis report with the W analysis now included! 
This report include a full write up of the W analysis codes, with input of plots of:
- exponential background fit
- TFractionFitter fit
- fit model

Additionally includes input of values for:
- calculated Z fractions
- fractions output from TFractionFitter
- numbers of events in each histogram (output as a table)

The top level script has been updated to include the W analysis, and I made a new python code to format the W analysis input for the report so that the W background code doesn't get too busy.

One question I had of something I noticed when writing up the report: I haven't included the kinematic cuts or isolation cut in the pion/kaon background analysis when plotting the `W{p,m}SingleTrackNoBias` histograms. Should I add these? I am assuming yes to the kinematic cuts, but I am unsure about the isolation cut (`TMath::Log10(TMath::Max(0.1,1.e-3*mu_PTSUMCONE040)) < 3`).

**Comment by mvesteri** [comment]
Thanks for sharing the draft document @lmcairns . I'm looking through that now, in advance of our weekly meeting.

Regarding the cuts for the pion/kaon plots: yes this is a good question to which there isn't a definite answer. What we want is a sample of pure pions/kaons that is representative of the background in our W selection. The problem is that this sample will be a cocktail of [pions,kaons,protons,fake tracks, heavy flavour children, muons/hadrons from EW processes,....]. If we don't apply the isolation cut then the sample isn't as representative of the background in our signal region. If we do apply it we greatly reduce the statistics and we may enhance the "pollution" from electroweak processes. Trying different choices here would be part of the assessment of the *systematic* uncertainties.

**Comment by lmcairns-mphys** [comment]
I have introduced a new program to calculate the W cross sections and the ratios. The calculated values are as follows:
Results_in_latex
#### Error Propagation
In terms of error propagation for the ratios, I am unsure whether to calculate the error using the total error on each cross section measurement, or whether it would be valid to just ignore the luminosity error and calculate with only the statistical error (and trigger efficiency at later date).
i.e. would it be valid to say for the W/W ratio:
Error_Eqn_Latex
and for the W/Z ratio:
WZ_Error_Eqn_Latex
since as the luminosity cancels out of the cross section calculation, could you set the luminosity error to zero, making any terms in the error propagation which include luminosity error also zero? (I have some written workings for these if you need to see them)
I have included in the results above the error calculated using the full cross section error, as well as the error calculated with only the statistical error in brackets.
#### Comparison of Results with Published Data
I did a quick comparison of these results with the ratios in the 7 TeV (http://arxiv.org/abs/1204.1620) and 8 TeV LHCb papers (http://arxiv.org/abs/1511.08039) .
The W/W ratio seems to agree quite well, especially with the 8 TeV paper:
- 5 TeV = 1.33
- 7 TeV = 1.27 ± 0.02 ± 0.01
- 8 TeV = 1.336 ± 0.004 ± 0.005 ± 0.002 

However the W/Z ratio is higher than these papers, although still relatively close.
- 5 TeV = 24.58 
- 7 TeV = 19.4 ± 0.5 ± 0.9
- 8 TeV = 20.13 ± 0.06 ± 0.11 ± 0.4
Judging by the difference in the W cross sections between the 7 and 8 TeV papers, to me this suggests that the W cross sections I have calculated might be too large, since my results are quite close to those at 7 TeV. Considering the large difference between 7 and 8, I would expect the difference between 5 and 7 to be larger (although I imagine this will become more clear with a plot of xsec against sqrt(s)!)

#### Next steps
My next steps are to write up these calculations and error propagation in the Analysis Report, and add the abstract/results sections as you suggested. Following that, I will produce the xsec vs sqrt(s) plot. I also intend to upload my electronic record of work done for Weeks 1 to 5 of Term 2 this weekend.

**Comment by mvesteri** [comment]
@lmcairns sorry for the slow response.
You are correct about the luminosity uncertainty. You can simply ignore it in any of the ratios. (If you tried to include the luminosity uncertainty it would drop out if you assume a 100% correlation (between different processes)).

Don't worry about the consistency of the ratios with the measurements at 7 and 8 TeV. We expect some scaling of these ratios with sqrts. Though it will be much weaker than the scaling of the individual cross sections. I.e. the W+,W-,Z cross sections should scale similarly with sqrts. 

Naively, I'd expect the Z cross section to scale a bit more quickly. This scaling is enhanced by the requirement that both children of the Z decay are in the LHCb acceptance. For the W it is only the [charged] child that has to be in acceptance. The neutrino can go anywhere.

**Comment by lmcairns-mphys** [comment]
@mvesteri 
I have updated the Analysis Report to include the 5 main results in an abstract and results section.
[measurement_report.pdf](https://github.com/r-preston/MPhysProject2021/files/5984745/measurement_report.pdf)

Additionally I have made a code to plot our 5 TeV values of cross section with the other published LHCb results. I have used the 2014 and 2015 values for 7 TeV, the 2016 values for 8 TeV, and the 2016 for 13 TeV in the Z plot. 
I intend to add these plots to the Analysis Report tomorrow with proper references for the published values (and to correct the published values currently quoted there as I used the 2012 values for 7 TeV).
Wp_xsec_plot
Wm_xsec_plot
Z_xsec_plot
As the cross sections need to match the kinematic region used, I have so far only used LHCb values as I believe this is the only experiment using this region. Should I include values from any other sources, and are there any additional LHCb values that I have missed? These plots feel quite bare at the moment 😅

**Comment by lmcairns-mphys** [comment]
@mvesteri 
A few updates and questions before I close this pull request and start working on the trigger efficiency and background improvement.

Most up to date version of the report: [measurement_report.pdf](https://github.com/r-preston/MPhysProject2021/files/6012021/measurement_report.pdf)

1. I have checked that the code runs correctly from a new checkout of the branch, and it does. It took roughly 15 seconds to run the entire analysis, including compilation of the scripts and the latex report.

2. I have updated the code which compares the Z data to the Z simulation (plot_MC_comparison.cpp) to compare the data to the 5 TeV simulation used in the W background analysis (5TeV_2015_24r1_Down_Z_Sim09d.root) rather than the 13 TeV simulation you suggested to use back in October/November when I first wrote this code (13TeV_2016_28r1_Down_Z_Sim09h.root). I have assumed that this would be more correct as it validates the specific simulation data that I actually in this analysis. I have updated the report to reflect this change. Was this correct to do?

3. I attempted to find the theoretical values for the published results to add to the comparison plots as you suggested. However the papers do not include the exact values which they use: the papers only include the theoretical values in plots such as the one below (from the 2015 7 TeV papers). These values are NNLO predictions given by "Fewz configured with various PDF sets": should I look into producing these myself (although I imagine this is outside of the scope of time I have left), do you think I could find the values anywhere, or should I just not include them?
Figure7_7TeV 

4. I have plotted the ratio comparisons with published data, and included both these comparisons and the xsec comparisons in the report. See the plots below:
WW_ratio_plot
WZ_ratio_plot

**Comment by lmcairns-mphys** [comment]
Hi @mvesteri,
I am closing this pull request so that I can upload the trigger efficiency changes, but please could you respond to the questions in the above comment?
Hopefully should have the trigger efficiency update uploaded this afternoon.

**Comment by mvesteri** [comment]
@lmcairns sorry for the delay. 

1.  👍 that sounds great
2. Yes we should be looking at the 5TeV data and simulation. That is most relevant/useful here
3. For the theory cross sections my colleagues reminded me that we also publish all figures in root `.C` format too. So you should be able to find the corresponding figure from, e.g, https://lhcbproject.web.cern.ch/lhcbproject/Publications/LHCbProjectPublic/LHCb-PAPER-2015-049.html  and extract the numerical values for all points. Don't worry about getting the theory prediction for the 5 TeV point. It is plenty enough to have the measurement, and to say that the next step would be for somebody to provide the theory prediction.

**Comment by mvesteri** [comment]
Actually my colleague (Will Barter) now reminded me that we have this figure https://lhcbproject.web.cern.ch/lhcbproject/Publications/LHCbProjectPublic/Directory_LHCb-PAPER-2015-049/supplementary/Fig10-S.pdf . We should be able to extract the points behind those theory curves

**Comment by mvesteri** [comment]
The `.C` file should be in https://cds.cern.ch/record/2108134/files/LHCb-PAPER-2015-049-supplementary.zip?version=1

**Pull request merged**
