### PR TITLE
W xsec improvement: Track Cut and Comparison Plots

### LINKED ISSUE #33: Fig10 Value Differences
Hi @mvesteri 

I checked the 8 TeV 2015 paper (https://arxiv.org/abs/1511.08039) again to get their sources, and found that the 7 TeV Z paper in 2015 (https://arxiv.org/abs/1505.07024) had updated values of the W xsecs using more precise efficiency values, so that explains the biggest discrepancy in the values in Fig10 vs the papers. However the differences in the errors use still remain, and there are two small differences in the exact values used, in the 7 TeV Wp xsec and the 8 TeV Wm xsec. I have highlighted these differences in bold. See the comparison below:

|                  | Fig10.C                | Values quoted in Papers |
|------|------|------|
| 7 TeV, W+ | **878.4 ± 16.6** | **878.0 ± 33.1** |
| 7 TeV, W-  | 689.5 ± 13.1       | 689.5 ± 25.4 |
| 7 TeV, Z     | 76.0 ± 1.3           | 76.0 ± 3.1 |
| 8 TeV, W+ | 1093.6 ± 18.3     | 1093.6 ± 32.9 |
| 8 TeV, W-  | **819.4 ± 13.0** | **818.4 ± 23.4** | 
| 8 TeV, Z     | 95.0 ± 1.7           | 95.0 ± 3.2 |

Checking the break down of the errors, it doesn't appear that one of the separated errors has been removed from the errors used in Fig10.C (ie. subtracting luminosity), but I may be wrong on this.

### LINKED ISSUE #35: W xsec improvement: Track Cut
@mvesteri 
I have done the initial steps of the track cut analysis, but have not yet calculated the new systematic errors it introduces. See analysis report using both the eta cuts and the track chi squared/ndf cut: [measurement_report.pdf](https://github.com/r-preston/MPhysProject2021/files/6070669/measurement_report.pdf)

The track cut has a clear improvement on the fitting of the K/pi background, as seen in the plots for Wm below, but as the slope is  lower than the value I previously manually set the slope to be (0.2), the overall fit model is not as accurate to the data as it used to be; the chi2/ndf is roughly doubled. See the comparison for Wm below; Wm shows the difference more clearly, whilst I think the Wp analysis suffers more from the limited statistics of the W signal simulation.

Wm, only eta cut:
W-_expo_back_plot_only_eta
Wm, both eta and track cuts:
W-_expo_back_plot_both
Wm fit model with manually fixed slope (0.2):
W-_fit_model_0 2
Wm fit model with track cut slope, not fixed:
W-_fit_model

The cross sections produced using this cut are reduced compared to fixing the slope, which although brings them closer to the expected theoretical values, it does mean that the 3 cross sections no longer differ from the theory
by roughly the same factor, so some error may originate in places other than the luminosity.

I had a few questions about how to proceed, as I have some issues:
1. I'm unsure what values I should be comparing in order to determine the systematic error introduced by this change: should I compare the cross section outputs, or the W signal fractions used to determine the cross sections? 
2. Furthermore, should I use the manual setting of the background slope in this comparison? I obviously won't use it in the value produced with this track cut, but I have had some errors when trying to perform the fraction fitting on Wp for the value without the track cut. If I do not manually set the slope of the Wp background fit (with only the eta cut), TFractionFitter does not run and a value is not produced. The error that occurs is `abnormal termination of minimization`, which can be fixed by using an initial value closer to the expected outcome, but I can't change this when using the slope from the fit without manually resetting it. I am unsure of the best way to fix this.
3. Is error on the signal fraction systematic? I've currently included it in the statistical error, as the signal fraction is used in calculation of number of W events for the xsec calculation, but I'm thinking this may not be correct?

(As an additional update, I have fixed the error propagation issues I referenced in #33, and have made progress with the comparison plots, although I am having some small issues with TMultiGraph that are slowing me down somewhat.)

### PR DESCRIPTION
**Pull request by lmcairns-mphys**
@mvesteri 
Please find the upload of the track cut W xsec improvement, alongside my current code for the comparison plots (unfinished).
Current analysis report: [measurement_report.pdf](https://github.com/r-preston/MPhysProject2021/files/6079618/measurement_report.pdf)

I have included the track cut in the background analysis with the pT < 30 GeV cut you suggested in #35, and was able to get a slope around the same value I previously set manually. I have been able to calculate the new cross sections and ratios from this improvement, as seen in the report above.
I have attempted to calculate the systematic error due to this change but I am unsure if I have done so correctly as the error it produces on the xsecs and ratios is unexpectedly large. This is shown in the table below (Table 2 in the report):
Systematic_unc_table

To calculate the track cut uncertainty, I determined the systematic error on the signal fraction within the W_background.cpp code, and then propagated it through the rest of the calculations. I am confident in the propagation, but not my initial calculation of the systematic error.
I have set the systematic error on the signal fraction to be the difference between the signal fraction with the track cut and without.

Additionally this pull request includes the comparison plots of the xsecs and ratios with published and theoretical values. I still have some additions to make to these and will upload them when made.
Closes #35.

### CODE REVIEW

**Comment by lmcairns-mphys** [comment]
The theory values have now been added to the WZ ratio plot in addition to the WW ratio plot. The x axis has been expanded to include the same range as the xsec comparison plots.
See analysis report, Figure 8 on page 12: [measurement_report.pdf](https://github.com/r-preston/MPhysProject2021/files/6079926/measurement_report.pdf)
WW_ratio_plot
WZ_ratio_plot
Further planned work for comparison plots:
- Change colour of 5 TeV points to indicate values determined in my analysis.
- Potentially change presentation of theoretical trend in ratio plots, as the error bars are visible. E.g. use the a4 plotting option of TGraphErrors.

**Comment by lmcairns-mphys** [comment]
@mvesteri 
I have updated the systematic uncertainty to be calculated as the difference between the signal fractions determined with the cuts pT < 25 GeV and pT < 35 GeV on the K/pi background. The results are still calculated using the cut at 30 GeV.
This does reduce the systematic errors, but they still strongly dominate (e.g. on Wm xec, it has changed from 15% to 13% as percentage errors.).
results_sys_unc_pt_cut
[measurement_report.pdf](https://github.com/r-preston/MPhysProject2021/files/6084564/measurement_report.pdf)

**Comment by lmcairns-mphys** [comment]
@mvesteri 
(oops meant to commit this Friday)
I have finished the formatting of the comparison plots, with the 5 TeV points highlighted in a different colour. These can be seen in the report below, with the WW ratio given as an example below.
[measurement_report.pdf](https://github.com/r-preston/MPhysProject2021/files/6104310/measurement_report.pdf)

Are the error bars visible on the theory in this figure acceptable? They are only visible on the theory in this plot, so I am hesitant to change the plotting method of the theory (eg. using "4") for this plot only, as the "c" option works well for the others.
WW_ratio_plot

Please can you confirm that the method of calculating systematic uncertainty in the previous comment is correct? (ie taking it to be the difference between the signal fractions determined with the cuts pT < 25 GeV and pT < 35 GeV on the K/pi background) 
The results found with these values are given in the previous comment and the report.
Is a ~10% systematic error acceptable? Should I reduce the range of the difference to make the error more reasonable (ie between 28 GeV and 32 GeV)?

**Comment by lmcairns-mphys** [comment]
Small update to include factor differences between 5 TeV experimental values and theoretical values from Fig10. All agree with a factor 1.6 difference within error. Analysis report updated to include this: [measurement_report.pdf](https://github.com/r-preston/MPhysProject2021/files/6104776/measurement_report.pdf)

**Comment by mvesteri** [comment]
👍 I think the systematic uncertainty is reasonable. The next step in the analysis would be to try and find a way to control this background shape more precisely. And perhaps to optimise the selection cuts to suppress the background. I think what you have is fine for now though.

Regarding the plot of the W+/W- ratio: 
* I'd suggest to use a wider (maybe 2-3x) y axis range, so we draw less attention to the statistical/numerical wiggles in the theory prediction. 
* In the legend I think the W+/W- and sqrts value are both redundant. (covered by the x- and y-axis labels/titles). So "your" point could just be labelled as "This MPhys project", for example.

**Comment by lmcairns-mphys** [comment]
I have updated the WW ratio plot to use roughly 2.3x the y range, as shown below. Please also find the latest verison of the analysis report.
WW_ratio_plot
[measurement_report.pdf](https://github.com/r-preston/MPhysProject2021/files/6111043/measurement_report.pdf)

With this update I will close this pull request, and focus working on the final report.
Closes #35, Closes #33

**Pull request merged**
